b1aseurl = "http://www.varunvarma.com"
title = "varunvarma"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Varun Varma"
    info = "design, develop, operate planetary scale distributed systems"
    description = "Varun Varma's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/varunvarma-bw.jpeg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    #footercontent = "Enter a text here."

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/varunvarma/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/v-varma/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/varma_v/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
